version: '3'

services:
  rabbitmq-1:
    image: pivotalrabbitmq/rabbitmq-stream
    hostname: rabbitmq-1
    ports:
      - 15672:15672
      - 5672:5672
    volumes:
      - "./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf"
    environment:
      - RABBITMQ_ERLANG_COOKIE=dummy

  rabbitmq-2:
    image: pivotalrabbitmq/rabbitmq-stream
    hostname: rabbitmq-2
    ports:
      - 15673:15672
      - 5673:5672
    volumes:
      - "./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf"
    environment:
      - RABBITMQ_ERLANG_COOKIE=dummy

  rabbitmq-3:
    image: pivotalrabbitmq/rabbitmq-stream
    hostname: rabbitmq-3
    ports:
      - 15674:15672
      - 5674:5672
    volumes:
      - "./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf"
    environment:
      - RABBITMQ_ERLANG_COOKIE=dummy

  load-balancer:
    image: haproxy:2.3
    volumes:
      - "./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro"
    ports:
      - 5555:5555
      - 8100:8100
    depends_on:
      - rabbitmq-1
      - rabbitmq-2
      - rabbitmq-3
